name: Data-Package
version: 0.01
abstract: Base class for packages that are purely data
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
  Class::Inspector: 1.07
  Param::Coerce: 0.06
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
