abstract: Base class for packages that are purely data
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Data-Package
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Inspector: 1.07
  Params::Coerce: 0.06
  perl: 5.005
version: 1.00
